name: function2

# Controls when the action will run.
on:
  push:
    paths:
      - 'function2/**'

jobs: 
  function2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Check files in repo
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 1
          
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
          
      - name: Download files from S3
        run: rclone copy s3flare:wvwa-graphs/scripts/wvwa-generate-graphs.R ${{ github.workspace }}/function2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Run automatic prediction file
        run:  | 
          docker run --rm hello-world
      
      - name: List function2 files
        run: ls ${{ github.workspace }}/function2
          
      #- name: Copy files to s3 buckets
      #  run: |
      #    rclone copy ${{ github.workspace }}/function2/c.csv s3flare:wvwa-graphs/outputs/
