name: function1

# Controls when the action will run.
on:
  workflow_dispatch

jobs: 
  function1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Check files in repo
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 1
          
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
          
      - name: Download files from S3
        run: rclone copy s3flare:wvwa-graphs/scripts/wvwa-generate-graphs.R ${{ github.workspace }}/function1
        
      - name: List function1 files
        run: ls ${{ github.workspace }}/function1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Run automatic prediction file
        run:  | 
          docker run --rm -v ${{ github.workspace }}:/csv/ yjungku/faasr_test
      
      - name: List function2 files
        run: ls ${{ github.workspace }}/function2
      
      # Commit files ,and push
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./function2/c.csv
          git commit -m "trigger_from_function1-$(date '+%Y-%m-%d-%T')"
          git push --force origin main
          
      #- name: Copy files to s3 buckets
      #  run: |
      #    rclone copy ${{ github.workspace }}/function2/c.csv s3flare:wvwa-graphs/outputs/
